[project]
name = "nookies-pings"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = ["curl-cffi>=0.14.0", "scrapy>=2.14.1", "selectolax>=0.4.6", "zendriver>=0.15.2"]

[tool.ruff]
indent-width = 2
